BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "LICENCE"."STORE_AUTHORITY_TABLE"';
  EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

CREATE TABLE "LICENCE"."STORE_AUTHORITY_TABLE"
(
  NAME VARCHAR2(128 BYTE),
  PRIMARY KEY ("NAME")
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "LICENCE"."STORE_USER_TABLE"';
  EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

CREATE TABLE "LICENCE"."STORE_USER_TABLE"
(
  USER_ID NUMBER NOT NULL ENABLE,
  LOGIN VARCHAR2(128 BYTE),
  PASSWORD VARCHAR2(128 BYTE),
  FIRST_NAME VARCHAR2(128 BYTE),
  LAST_NAME VARCHAR2(128 BYTE),
  ACTIVATED NUMBER(1),
  LANG_KEY VARCHAR2(128 BYTE),
  IMAGE_URL VARCHAR2(128 BYTE),
  ACTIVATION_KEY VARCHAR2(128 BYTE),
  RESET_KEY VARCHAR2(128 BYTE),
  RESET_DATE VARCHAR2(128 BYTE),
  AUTHORITY_NAME VARCHAR2(128 BYTE),
  PRIMARY KEY ("USER_ID")
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "LICENCE"."STORE_RIGHT_TABLE"';
  EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

CREATE TABLE "LICENCE"."STORE_RIGHT_TABLE"
(
  RIGHT_ID NUMBER NOT NULL ENABLE,
  RIGHT_NAME VARCHAR2(128 BYTE),
  RIGHT_CODE VARCHAR2(128 BYTE),
  PRIMARY KEY ("RIGHT_ID")
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "LICENCE"."STORE_FILE_TABLE"';
  EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

CREATE TABLE "LICENCE"."STORE_FILE_TABLE"
(
  FILE_ID NUMBER NOT NULL ENABLE,
  USER_CODE VARCHAR2(128 BYTE),
  FILE_NAME VARCHAR2(128 BYTE),
  FILE_URL VARCHAR2(128 BYTE),
  FILE_TYPE VARCHAR2(128 BYTE),
  DIRECTORY_ID NUMBER,
  RIGHT_ID NUMBER,
  PRIMARY KEY ("FILE_ID")
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "LICENCE"."STORE_DIRECTORY_TABLE"';
    EXCEPTION
    WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

CREATE TABLE "LICENCE"."STORE_DIRECTORY_TABLE"
(
    FILE_ID NUMBER NOT NULL ENABLE,
    USER_CODE VARCHAR2(128 BYTE),
    DIRECTORY_NAME VARCHAR2(128 BYTE),
    RIGHT_ID VARCHAR2(128 BYTE),
    DIRECTORY_ID NUMBER,
    PRIMARY KEY ("FILE_ID")
)
